name: 'report-curator'
description: 'Under construction'
inputs:
  auth_token:
    description: "Access token to get the data about the repository."
    required: true
    default: ''
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
