name: 'report-curator'
description: 'Under construction'
inputs:
  auth_token:
    description: "Access token to get the data about the repository."
    required: true
    default: ''
  report_branch:
    description: "Branch to store the report related UI files"
    required: false
    default: 'report'
  report_theme:
    description: "Frontend theme of the generated report"
    required: false
    default: 'emerald'
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
