on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/checkout@v2
      - uses: ./
        with:
          who-to-greet: 'Ashutosh'
          auth_token: ${{ secrets.CURATOR_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
