on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ashutosh1919/report-curator@v0.0.5
        with:
          who-to-greet: 'Ashutosh'
          auth_token: ${{ secrets.CURATOR_TOKEN }}
          report_theme: 'blue'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
